Extraction moteur dans une librairie separé
PFE-A23/Lines pull request #21
Opened 2023-10-21 14:38 UTC by nicolaslabinebouchard

2023-10-21 14:49 UTC, mvsrgc requested changes

2023-10-21 14:49 UTC, mvsrgc commented on GraphicsEngine/include/IGraphicsEngine.h
> +    // virtual void drawTexture() = 0;
Est-ce qu'on peut supprimer ces lignes?

2023-10-21 14:49 UTC, mvsrgc commented on linesCore/Node.cpp
> +#include "../GraphicsEngine/GraphicsEngine.h"
Est-ce que ces lignes peuvent etre changées pour #include <GraphicsEngine/GraphicsEngine.h> ?

2023-10-21 14:49 UTC, mvsrgc commented on GraphicsEngine/include/IGraphicsEngine.h
> +#include "../linesCore/PolygonData.h"
Même chose ici

2023-10-21 15:15 UTC, nicolaslabinebouchard commented on linesCore/Node.cpp
> +#include "../GraphicsEngine/GraphicsEngine.h"
Ca serait vraiment plus propre mais je ne sais pas comment faire présentement. Il y a probablement une erreur dans la config CMake ( du sous-projet ou du projet principal ).

2023-10-22 23:05 UTC, mvsrgc approved these changes

2023-10-22 23:06 UTC, merged